# Generated by Django 4.1.5 on 2023-03-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_coordinates', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.FloatField(verbose_name='Relative Humidity')),
                ('lux_ir', models.IntegerField(verbose_name='IR Intensity')),
                ('lux_vis_ir', models.IntegerField(verbose_name='Visible+IR Intensity')),
                ('timestamp', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thlmonitor.sensorlocation')),
            ],
        ),
    ]
