# Generated by Django 4.1.5 on 2023-03-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(choices=[(0, 'Ground'), (1, 'First')])),
                ('grid_column', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2)),
                ('grid_rows', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')])),
                ('simple_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.FloatField(verbose_name='Relative Humidity')),
                ('lux_ir', models.IntegerField(verbose_name='IR Intensity')),
                ('lux_vis_ir', models.IntegerField(verbose_name='Visible+IR Intensity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thlmonitor.sensorlocation')),
            ],
        ),
    ]
